name: deploy
on:
  push:
    branches:
      - 'staging'
      - 'production'
jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1
      - name: Output branch name
        run: |
          echo "branch name: ${BRANCH_NAME}"
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.25
      - name: Initialise terraform
        run: terraform init
        working-directory: ./terraform
      - name: Initialise terraform
        run: terraform workspace select ${BRANCH_NAME} || terraform workspace new ${BRANCH_NAME}
        working-directory: ./terraform
      - name: Plan terraform
        run: terraform plan -out=plan.out
        working-directory: ./terraform
      - name: Execute terraform
        run: terraform apply -auto-approve plan.out
        working-directory: ./terraform
      - uses: chrislennon/action-aws-cli@v1.1
      - run: upload static files to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          with:
            args: aws s3 sync --delete src s3://`terraform output bucket_name`
        working-directory: ./terraform
